from datetime import datetime

u = User(username='conno', email='connor@connor.com')
u.set_password('1234')
db.session.add(u)
org = Organization(name="Capital One", location="USA", size="Large", domain="Financial")
db.session.add(org)

ass = Assessment(organization=org, user=u, timestamp=datetime.utcnow)
db.session.add(ass)
ass1 = Assessment(organization=org, user=u, timestamp=datetime.utcnow)
db.session.add(ass1)

cat = Category(name="Strategic Alignment")
db.session.add(cat)
q = Question(name="Current competitive differentiation in products & Services", category=cat)
db.session.add(q)
ql1 = QuestionList(assessment=ass, rating="2", question=q)
ql2 = QuestionList(assessment=ass1, rating="1", question=q)
db.session.add(ql1)
db.session.add(ql2)

q = Question(name="Clarity in Definition of Vision & Goals", category=cat)
db.session.add(q)
ql1 = QuestionList(assessment=ass, rating="1", question=q)
ql2 = QuestionList(assessment=ass1, rating="1", question=q)
db.session.add(ql1)
db.session.add(ql2)

q = Question(name="Identification of external and internal risks which may disrupt the business", category=cat)
db.session.add(q)
ql1 = QuestionList(assessment=ass, rating="1", question=q)
ql2 = QuestionList(assessment=ass1, rating="3", question=q)
db.session.add(ql1)
db.session.add(ql2)

q = Question(name="Does organization has an appreciation of emerging trends which may impact"
                  " the current business models?", category=cat)
db.session.add(q)
ql1 = QuestionList(assessment=ass, rating="1", question=q)
ql2 = QuestionList(assessment=ass1, rating="1", question=q)
db.session.add(ql1)
db.session.add(ql2)


cat = Category(name="How well do you understand your customer?")
db.session.add(cat)
q = Question(name="Does Customer recognize your products and services well?", category=cat)
db.session.add(q)
ql1 = QuestionList(assessment=ass, rating="1", question=q)
ql2 = QuestionList(assessment=ass1, rating="1", question=q)
db.session.add(ql1)
db.session.add(ql2)

q = Question(name="Net promoter Score across various product line against competition", category=cat)
db.session.add(q)
ql1 = QuestionList(assessment=ass, rating="3", question=q)
ql2 = QuestionList(assessment=ass1, rating="1", question=q)
db.session.add(ql1)
db.session.add(ql2)

q = Question(name="Feedback Mechanism developed with Customers?", category=cat)
db.session.add(q)
ql1 = QuestionList(assessment=ass, rating="2", question=q)
ql2 = QuestionList(assessment=ass1, rating="1", question=q)
db.session.add(ql1)
db.session.add(ql2)

q = Question(name="Customer Loyalty and Stickiness to products & services", category=cat)
db.session.add(q)
ql1 = QuestionList(assessment=ass, rating="2", question=q)
ql2 = QuestionList(assessment=ass1, rating="1", question=q)
db.session.add(ql1)
db.session.add(ql2)

q = Question(name="Can you track and monitor customer experience?", category=cat)
db.session.add(q)
ql1 = QuestionList(assessment=ass, rating="1", question=q)
ql2 = QuestionList(assessment=ass1, rating="1", question=q)
db.session.add(ql1)
db.session.add(ql2)


cat = Category(name="User Stories / Requirements")
db.session.add(cat)
q = Question(name="Time to market for Product/Service Delivery against competition", category=cat)
db.session.add(q)
ql1 = QuestionList(assessment=ass, rating="0", question=q)
ql2 = QuestionList(assessment=ass1, rating="1", question=q)
db.session.add(ql1)
db.session.add(ql2)

q = Question(name="Do you employ or value the concept of MVP and/or rapid prototyping?", category=cat)
db.session.add(q)
ql1 = QuestionList(assessment=ass, rating="1", question=q)
ql2 = QuestionList(assessment=ass1, rating="1", question=q)
db.session.add(ql1)
db.session.add(ql2)

q = Question(name="Are key design principles and functionality integrated today to deliver a consistent experience? ", category=cat)
db.session.add(q)
ql1 = QuestionList(assessment=ass1, rating="1", question=q)
ql2 = QuestionList(assessment=ass, rating="2", question=q)
db.session.add(ql1)
db.session.add(ql2)

q = Question(name="Is your current experience compliant with key"
                  " guidelines and regulations (e.g. accessibility, security)?", category=cat)
db.session.add(q)
ql1 = QuestionList(assessment=ass1, rating="1", question=q)
ql2 = QuestionList(assessment=ass, rating="3", question=q)
db.session.add(ql1)
db.session.add(ql2)

q = Question(name="Have you developed customer personas for your products and Services?", category=cat)
db.session.add(q)
ql1 = QuestionList(assessment=ass1, rating="1", question=q)
ql2 = QuestionList(assessment=ass, rating="2", question=q)
db.session.add(ql1)
db.session.add(ql2)


cat = Category(name="People and Organization")
db.session.add(cat)
q = Question(name="How are your current organizational capabilities aligned to support your business objectives?", category=cat)
db.session.add(q)
ql1 = QuestionList(assessment=ass1, rating="1", question=q)
ql2 = QuestionList(assessment=ass, rating="1", question=q)
db.session.add(ql1)
db.session.add(ql2)

q = Question(name="Have you done a gap mapping for technology/business skillsets and requirements?", category=cat)
db.session.add(q)
ql1 = QuestionList(assessment=ass1, rating="1", question=q)
ql2 = QuestionList(assessment=ass, rating="2", question=q)
db.session.add(ql1)
db.session.add(ql2)

q = Question(name="Is your team equipped to use insights from Data to make smart business decisions?", category=cat)
db.session.add(q)
ql1 = QuestionList(assessment=ass1, rating="1", question=q)
ql2 = QuestionList(assessment=ass, rating="0", question=q)
db.session.add(ql1)
db.session.add(ql2)

q = Question(name="What is your current employee engagement level?", category=cat)
db.session.add(q)
ql1 = QuestionList(assessment=ass1, rating="1", question=q)
ql2 = QuestionList(assessment=ass, rating="1", question=q)
db.session.add(ql1)
db.session.add(ql2)

q = Question(name="Have you developed customer personas for your products and Services?", category=cat)
db.session.add(q)
ql1 = QuestionList(assessment=ass1, rating="1", question=q)
ql2 = QuestionList(assessment=ass, rating="2", question=q)
db.session.add(ql1)
db.session.add(ql2)


cat = Category(name="Technology")
db.session.add(cat)
q = Question(name="How well does your current technology infrastructure "
                  "& systems  support your business goals & Vision?", category=cat)
db.session.add(q)
ql1 = QuestionList(assessment=ass1, rating="1", question=q)
ql2 = QuestionList(assessment=ass, rating="2", question=q)
db.session.add(ql1)
db.session.add(ql2)

q = Question(name="Cloud Adoption Level for Scalability & Cost Optimization ", category=cat)
db.session.add(q)
ql1 = QuestionList(assessment=ass1, rating="1", question=q)
ql2 = QuestionList(assessment=ass, rating="1", question=q)
db.session.add(ql1)
db.session.add(ql2)

q = Question(name="Open Source Adoption ", category=cat)
db.session.add(q)
ql1 = QuestionList(assessment=ass1, rating="1", question=q)
ql2 = QuestionList(assessment=ass, rating="3", question=q)
db.session.add(ql1)
db.session.add(ql2)

q = Question(name="Level for Automation within operations landscape", category=cat)
db.session.add(q)
ql1 = QuestionList(assessment=ass1, rating="1", question=q)
ql2 = QuestionList(assessment=ass, rating="1", question=q)
db.session.add(ql1)
db.session.add(ql2)

q = Question(name="Use of Analytics/AI/Machine Learning for Insightful business decisions", category=cat)
db.session.add(q)
ql1 = QuestionList(assessment=ass1, rating="1", question=q)
ql2 = QuestionList(assessment=ass, rating="1", question=q)
db.session.add(ql1)
db.session.add(ql2)


org = Organization(name="Wipro Limited", location="India", size="Large", domain="IT")
db.session.add(org)
db.session.commit()
exit()