"""testing removal of assessmenttemplate

Revision ID: 27b46faca79b
Revises: 5c138af8b84f
Create Date: 2019-09-24 17:55:10.263088

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27b46faca79b'
down_revision = '5c138af8b84f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('assessment_template')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assessment_template',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('questions', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user_account.id'], name='assessment_template_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='assessment_template_pkey'),
    sa.UniqueConstraint('name', name='assessment_template_name_key')
    )
    # ### end Alembic commands ###
