"""changed questionlist to assessment detail

Revision ID: 39915bd8cfa2
Revises: 8c25d54daa06
Create Date: 2019-09-23 20:25:03.732965

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39915bd8cfa2'
down_revision = '8c25d54daa06'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assessment_detail',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assessment_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessment.id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['question.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('question_list')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('question_list',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('assessment_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('question_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('rating', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessment.id'], name='question_list_assessment_id_fkey'),
    sa.ForeignKeyConstraint(['question_id'], ['question.id'], name='question_list_question_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='question_list_pkey')
    )
    op.drop_table('assessment_detail')
    # ### end Alembic commands ###
