"""renamed association

Revision ID: 5c138af8b84f
Revises: aec23b8be5bc
Create Date: 2019-09-24 13:39:33.631789

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c138af8b84f'
down_revision = 'aec23b8be5bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category_list',
    sa.Column('org_id', sa.Integer(), nullable=True),
    sa.Column('cat_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cat_id'], ['category.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organization.id'], )
    )
    op.drop_table('association')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('association',
    sa.Column('org_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('cat_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['cat_id'], ['category.id'], name='association_cat_id_fkey'),
    sa.ForeignKeyConstraint(['org_id'], ['organization.id'], name='association_org_id_fkey')
    )
    op.drop_table('category_list')
    # ### end Alembic commands ###
