"""created association table the correct way

Revision ID: aec23b8be5bc
Revises: 39915bd8cfa2
Create Date: 2019-09-24 13:37:17.043228

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aec23b8be5bc'
down_revision = '39915bd8cfa2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('association',
    sa.Column('org_id', sa.Integer(), nullable=True),
    sa.Column('cat_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cat_id'], ['category.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organization.id'], )
    )
    op.drop_table('category_list')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category_list',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('org_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('cat_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['cat_id'], ['category.id'], name='category_list_cat_id_fkey'),
    sa.ForeignKeyConstraint(['org_id'], ['organization.id'], name='category_list_org_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='category_list_pkey')
    )
    op.drop_table('association')
    # ### end Alembic commands ###
